const tenses: TTenses[] = [
  "INDICATIVE_PRESENT",
  "INDICATIVE_IMPERFECT",
  "INDICATIVE_PRETERITE",
  "INDICATIVE_FUTURE",
  "INDICATIVE_PERFECT",
  "INDICATIVE_PLUPERFECT",
  "INDICATIVE_FUTURE_PERFECT",
  "INDICATIVE_PRETERITE_PERFECT",
  "SUBJUNCTIVE_PRESENT",
  "SUBJUNCTIVE_IMPERFECT_RA",
  "SUBJUNCTIVE_IMPERFECT_SE",
  "SUBJUNCTIVE_FUTURE",
  "SUBJUNCTIVE_PERFECT",
  "SUBJUNCTIVE_PLUPERFECT",
  "SUBJUNCTIVE_FUTURE_PERFECT",
  "CONDITIONAL_PRESENT",
  "CONDITIONAL_PERFECT"
];

type TTenses = "INDICATIVE_PRESENT" |
  "INDICATIVE_IMPERFECT" |
  "INDICATIVE_PRETERITE" |
  "INDICATIVE_FUTURE" |
  "INDICATIVE_PERFECT" |
  "INDICATIVE_PLUPERFECT" |
  "INDICATIVE_FUTURE_PERFECT" |
  "INDICATIVE_PRETERITE_PERFECT" |
  "SUBJUNCTIVE_PRESENT" |
  "SUBJUNCTIVE_IMPERFECT_RA" |
  "SUBJUNCTIVE_IMPERFECT_SE" |
  "SUBJUNCTIVE_FUTURE" |
  "SUBJUNCTIVE_PERFECT" |
  "SUBJUNCTIVE_PLUPERFECT" |
  "SUBJUNCTIVE_FUTURE_PERFECT" |
  "CONDITIONAL_PRESENT" |
  "CONDITIONAL_PERFECT"

const verbs = [
  "ser",
  "estar",
  "haber",
  "tener",
  "ir",
  "saber",
  "dar",
  "hacer",
  "poder",
  "decir",
  "caminar",
  "hablar",
  "tomar",
  "vender",
  "correr",
  "comer",
  "beber",
  "aprender",
  "vivir"
];

export { tenses, type TTenses, verbs }